spring:
  application:
    name: config-server
---
#服务配置
spring:
  profiles: config-server1
#应用配置
  cloud:
    config:
      label: master #git label(提交id,分支名称或tag)
      server:
        git:
          password: '' #登录密码
          searchPaths: common-config #搜寻目录，可以配置多个，用逗号分割
          uri: https://github.com/jackyang104873858/Springcloudtraining #仓库地址
          username: '' #登录用户
server:
  port: '8888'
---
#服务配置
spring:
  profiles: config-server2
#应用配置
  cloud:
    config:
      label: master #git label(提交id,分支名称或tag)
      server:
        git:
          password: '' #登录密码
          searchPaths: common-config #搜寻目录，可以配置多个，用逗号分割
          uri: https://github.com/jackyang104873858/Springcloudtraining #仓库地址
          username: '' #登录用户
server:
  port: '8889'          
---
#服务配置
spring:
  profiles: config-server3
#应用配置
  cloud:
    config:
      label: master #git label(提交id,分支名称或tag)
      server:
        git:
          password: '' #登录密码
          searchPaths: common-config #搜寻目录，可以配置多个，用逗号分割
          uri: https://github.com/jackyang104873858/Springcloudtraining #仓库地址
          username: '' #登录用户
server:
  port: '8890'
    