spring:
  application:
    name: discovery-cluster
---
spring:
  profiles: server1
server:
  port: 8761
eureka:
  instance:
    hostname: server1
  client:
    service-url:
      default-zone: http://server1:8761/eureka/,http://server1:8762/eureka/,http://server1:8763/eureka/

---
spring:
  profiles: server2
server:
  port: 8762
eureka:
  instance:
    hostname: server2
  client:
    service-url:
      default-zone: http://server1:8761/eureka/,http://server1:8762/eureka/,http://server1:8763/eureka/

---
spring:
  profiles: server3
server:
  port: 8763
eureka:
  instance:
    hostname: server3
  client:
    service-url:
      default-zone: http://server1:8761/eureka/,http://server1:8762/eureka/,http://server1:8763/eureka/