#服务配置
server:
  port: '8888'
  
spring:
  application:
    name: config-server
#应用配置
  cloud:
    config:
      label: master #git label(提交id,分支名称或tag)
      server:
        git:
          password: '' #登录密码
          searchPaths: common-config #搜寻目录
          uri: https://github.com/jackyang104873858/Springcloudtraining #仓库地址
          username: '' #登录用户
          
        #svn:
          #uri: http://192.168.0.6/svn/repo/config-repo
          #username: username
          #password: password
        #default-label: trunk
  #profiles:
    #active: subversion
    
          
          
          
#eureka服务注册地址
eureka:
  client:
    serviceUrl:
          defaultZone: http://localhost:8010/eureka/